### PR TITLE
support for env w/o ping6 command and japanese env

### PR DESCRIPTION
**Pull request by panakuma**
1.support environment with out ping6 command
Supported to work in the environment without ping6 command like Archlinux.

2.support environment japanese env
Supported to work in the environment with LANG=ja_JP.UTF-8

### CODE REVIEW

**Comment by upa** [comment]
Thank you for the pr. The current locale handling `locale.setlocale` should be refactored (I had implemented it without correct understanding).  But implementing locale-dependent code is not good, because it would be endless.

Anyway, I'd like to reproduce the situation you faced. What is your environment? Archlinux installed with Japanese?

**Comment by panakuma** [comment]
> But implementing locale-dependent code is not good, because it would be endless.

Indeed, that's right.
It was a bad idea to have a stupid implementation.

> What is your environment? Archlinux installed with Japanese?

My environment is as follows
- `/etc/os-release`
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```
- `/etc/locale.gen`
```
en_US.UTF-8 UTF-8  
ja_JP.UTF-8 UTF-8
```
- `/etc/locale.conf`
```
LANG=ja_JP.UTF-8
```
- `~$ uname -a`
```
Linux arch 5.15.32-1-lts #1 SMP Mon, 28 Mar 2022 08:54:31 +0000 x86_64 GNU/Linux
```
- `~$ echo $LANG`
```
ja_JP.UTF-8
```
image

**Comment by upa** [comment]
Hi. Thanks for the info. I have reproduced it and fixed by commit https://github.com/upa/deadman/commit/bff1335472a2b21d2dd0486b4b449b4537fe9cf0. Could you confirm that it works on your env?

**Comment by panakuma** [comment]
I checked the fix and it worked fine.
Thank you for your support.

This PR will be closed.

**Pull request closed without merging**
